begin;

create table if not exists clients
(
    id                        integer primary key generated by default as identity,
    group_id                  integer unique,
    gitlab_token              varchar(50)  not null,
    webhook_url               varchar(100) not null,
    created_at                timestamp    not null,
    updated_at                timestamp    not null,
    discussion_firing_timeout varchar(10) not null default ''
);

commit;
